version: '3.3'

services:
  backend:
    build: ./code/backend
    expose:
     - 4000
    ports:
      - 4000:4000
    volumes:
      - ./code/backend:/usr/src/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - LD_LIBRARY_PATH=/usr/instant_client/instantclient_21_7/
  ui:
    build: ./code/ui
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./code/ui/src/:/usr/src/ui/src
      - ./code/ui/public/:/usr/src/ui/public
    links:
      - "backend:backend"
